version: "3"
services:
  backend:
    build: ./spring-boot-crud
    container_name: backend
    depends_on:
      - postgresql
    restart: ${RESTART_POLICY}
    environment:
      - TZ
      - SERVER_PORT
      - API_BASE_PATH
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 9090:${SERVER_PORT}

  postgresql:
    image: postgres:11.4
    container_name: postgresql
    restart: ${RESTART_POLICY}
    environment:
      - TZ
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    command: "
                postgres
                  -c max_connections=200
                  -c logging_collector=on
                  -c log_min_messages=LOG
                  -c log_directory=/var/log/postgresql"
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql-data:/var/lib/postgresql/data:Z

  frontend:
    build: ./react-hooks-crud
    container_name: frontend
    restart: ${RESTART_POLICY}
    ports:
      - 9091:80

  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    restart: ${RESTART_POLICY}
    links:
      - backend
      - frontend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:Z
    ports:
      - 80:80